api_platform:
    mapping:
        paths:
#            - '%kernel.project_dir%/src/Entity' ENTITIES SHOULDN'T BE PUBLIC API ENDPOINTS
            - '%kernel.project_dir%/src/ApiResource'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    collection:
        pagination:
            enabled: true
